// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/*
 * sandbox.c: User-space loader for the curl sandbox.
 *
 * This program:
 * 1. Loads and attaches the eBPF program (sandbox.bpf.c).
 * 2. Resolves whitelisted domains (NET-001) to IPs.
 * 3. Populates the `allowed_ips` eBPF map.
 * 4. Listens for violation logs from the kernel via a ring buffer.
 * 5. Forks and executes 'curl' with the user's arguments.
 * 6. Adds the new curl PID to the `sandboxed_pid` map so the kernel
 * knows which process to trace.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <errno.h>
#include <sys/ptrace.h>
#include <signal.h>
#include <pwd.h>
#include <sys/inotify.h> // For file watcher
#include <poll.h>


#include <bpf/libbpf.h>
#include "handler.h"
#include "handler.skel.h" // Generated by libbpf-bootstrap

#include <cjson/cJSON.h>
// --- Ring Buffer Callback ---

/*
 * Converts a policy ID enum to a human-readable string.
 */
const char *policy_to_string(enum policy_id p)
{
	switch (p) {
	case POLICY_NET_001_WHITELIST:
		return "NET-001 (Whitelist)";
	case POLICY_NET_002_FAMILY:
		return "NET-002 (Protocol Family)";
	case POLICY_NET_005_PRIVATE_IP:
		return "NET-005 (Private IP)";
	case POLICY_NET_006_PORT:
		return "NET-006 (Port)";
	// NEW: Add FS policies
	case POLICY_FS_001_WRITE_PATH:
		return "FS-001 (Write Path)";
	case POLICY_FS_006_SYS_PATH:
		return "FS-006 (System Path)";
	default:
		return "Unknown";
	}
}

/*
 * Converts an IP address from __u32 (host byte order) to a string.
 */
static char *ip_to_string(__u32 ip)
{
	static __thread char ip_str[INET_ADDRSTRLEN];
	struct in_addr addr = { .s_addr =
					htonl(ip) }; // Convert back to network order for inet_ntop
	inet_ntop(AF_INET, &addr, ip_str, sizeof(ip_str));
	return ip_str;
}

static volatile bool exiting = false;

static void sig_handler(int sig)
{
    exiting = true;
}


/*
 * Callback function to process violation events from the ring buffer.
 */
static int handle_event(void *ctx, void *data, size_t data_sz)
{
	const struct log_event *e = data;

	fprintf(stderr, "\n--- POLICY VIOLATION ---\n");
	fprintf(stderr, "  PID: %d\n", e->pid);
	fprintf(stderr, "  Command: %s\n", e->comm);
	fprintf(stderr, "  Policy: %s\n", policy_to_string(e->policy_id));

	// NEW: Handle different event types
	switch (e->type) {
	case EVENT_NET:
		fprintf(stderr, "  Target: %s:%d\n", ip_to_string(e->net.dest_ip),
			e->net.dest_port);
		break;
	case EVENT_FS:
		fprintf(stderr, "  Target: %s\n", e->fs.path);
		break;
	default:
		fprintf(stderr, "  Target: Unknown event data\n");
	}

	fprintf(stderr, "--------------------------\n");

	return 0;
}

// --- Main Application ---

static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args)
{
	// You can adjust this to LIBBPF_DEBUG for more verbosity
	if (level >= LIBBPF_WARN)
		return vfprintf(stderr, format, args);
	return 0;
}

/*
 * Helper to clear a BPF_MAP_TYPE_HASH.
 */
static void clear_hash_map(struct bpf_map *map)
{
    size_t key_size = bpf_map__key_size(map);
    void *keys[128]; // Max entries from map definition
    int max_keys = 128;
    int key_count = 0;
    void *prev_key = NULL;
    
    printf("[Debug]   -> Clearing HASH map (fd %d, key_size %zu)...\n", bpf_map__fd(map), key_size);

    // 1. Collect all keys
    void *current_key = calloc(1, key_size);
    if (!current_key) return;

    // Use bpf_map__get_next_key with correct signature including key_size
    while (bpf_map__get_next_key(map, prev_key, current_key, key_size) == 0) {
        if (key_count < max_keys) {
            keys[key_count] = calloc(1, key_size);
            if (!keys[key_count]) break; // Out of memory
            memcpy(keys[key_count], current_key, key_size);
            key_count++;
        }
        prev_key = current_key;
    }
    free(current_key);

    // 2. Delete all collected keys
    // This function correctly takes key_size
    for (int i = 0; i < key_count; i++) {
        bpf_map__delete_elem(map, keys[i], key_size, BPF_ANY);
        free(keys[i]);
    }
    printf("[Debug]   -> Cleared %d HASH entries.\n", key_count);
}

/*
 * Helper to clear a BPF_MAP_TYPE_LPM_TRIE.
 */
static void clear_lpm_map(struct bpf_map *map)
{
    size_t key_size = bpf_map__key_size(map);
    void *keys[16]; // Max entries from map definition
    int max_keys = 16;
    int key_count = 0;
    void *prev_key = NULL;

    printf("[Debug]   -> Clearing LPM map (fd %d, key_size %zu)...\n", bpf_map__fd(map), key_size);

    // 1. Collect all keys
    void *current_key = calloc(1, key_size);
    if (!current_key) return;

    // Use bpf_map__get_next_key with correct signature including key_size
    while (bpf_map__get_next_key(map, prev_key, current_key, key_size) == 0) {
        if (key_count < max_keys) {
            keys[key_count] = calloc(1, key_size);
            if (!keys[key_count]) break;
            memcpy(keys[key_count], current_key, key_size);
            key_count++;
        }
        prev_key = current_key;
    }
    free(current_key);

    // 2. Delete all collected keys
    // This function correctly takes key_size
    for (int i = 0; i < key_count; i++) {
        bpf_map__delete_elem(map, keys[i], key_size, BPF_ANY);
        free(keys[i]);
    }
    printf("[Debug]   -> Cleared %d LPM entries.\n", key_count);
}

/*
 * Helper to clear the command_to_sandbox map (by setting to empty string)
 */
static void clear_command_map(struct bpf_map *map)
{
    printf("[Debug]   -> Clearing command map...\n");
    __u32 zero_key = 0;
    char cmd_buf[MAX_COMMAND_LEN] = {}; // Empty string
    bpf_map__update_elem(map, &zero_key, sizeof(zero_key), &cmd_buf, sizeof(cmd_buf), BPF_ANY);
}


static int load_policy_from_json(struct handler_bpf *skel, const char *json_path)
{
	char *buffer;
	FILE *f;
	long f_size;
	int err = 0;

	printf("[Daemon] Clearing all old policies...\n");
    clear_command_map(skel->maps.command_to_sandbox);
    clear_hash_map(skel->maps.allowed_ips);
    clear_lpm_map(skel->maps.allowed_write_paths);
    clear_hash_map(skel->maps.blocked_env_keys);
	clear_hash_map(skel->maps.policy_toggle_map);

	f = fopen(json_path, "r");
	if (!f) {
		fprintf(stderr, "[Loader] Failed to open policy file %s: %s\n", json_path,
			strerror(errno));
		return -1;
	}

	fseek(f, 0, SEEK_END);
	f_size = ftell(f);
	fseek(f, 0, SEEK_SET);

	buffer = malloc(f_size + 1);
	if (!buffer) {
		fprintf(stderr, "[Loader] Failed to allocate memory for policy file\n");
		fclose(f);
		return -1;
	}
	fread(buffer, 1, f_size, f);
	fclose(f);
	buffer[f_size] = 0;

	printf("[Loader] Read %ld bytes from %s\n", f_size, json_path);

	cJSON *root = cJSON_Parse(buffer);
	if (!root) {
		fprintf(stderr, "[Loader] Failed to parse JSON: %s\n", cJSON_GetErrorPtr());
		free(buffer);
		return -1;
	}

	printf("[Loader] Successfully parsed policy JSON.\n");

	// --- 0. Populate Command to Sandbox (SEC-001) ---
    printf("[Daemon] Loading Command to Sandbox...\n");
    cJSON *command_obj = cJSON_GetObjectItem(root, "command");
    if (cJSON_IsString(command_obj)) {
        const char* command_str = cJSON_GetStringValue(command_obj);
        char command_buf[MAX_COMMAND_LEN] = {};
        strncpy(command_buf, command_str, MAX_COMMAND_LEN - 1);
        __u32 key = 0;

        err = bpf_map__update_elem(skel->maps.command_to_sandbox, &key, sizeof(key), command_buf, sizeof(command_buf), BPF_ANY);
        if (err) {
            fprintf(stderr, "[Debug]   -> ERROR adding command to map: %s\n", strerror(errno));
        } else {
            printf("[Debug]   -> Set command to sandbox: '%s'\n", command_buf);
        }
    } else {
        printf("[Daemon] 'command' key not found or not a string.\n");
    }

	// --- 1. Populate Network Policy (NET-001) ---
	printf("[Loader] Loading Network Policies (NET-001)...\n");

	// FIX: Get the "network_policies" object first
	cJSON *net_policies = cJSON_GetObjectItem(root, "network_policies");
	cJSON *domains_array = NULL;
	if (cJSON_IsObject(net_policies)) {
		// FIX: Now get "allowed_domains" from *that* object
		domains_array = cJSON_GetObjectItem(net_policies, "allowed_domains");
	}

	if (cJSON_IsArray(domains_array)) {

		int array_size = cJSON_GetArraySize(domains_array);

		if (array_size == 1) {
			cJSON *first = cJSON_GetArrayItem(domains_array, 0);
			const char *domain = cJSON_GetStringValue(first);
			if (domain && strcmp(domain, "*") == 0) {
				printf("[Loader] Network wildcard detected\n");
				__u32 net_key = TOGGLE_KEY_NET;
				__u32 wildcard_val = 1; // Value doesn't matter, just presence
				bpf_map__update_elem(skel->maps.policy_toggle_map, &net_key, 
									sizeof(net_key), &wildcard_val, sizeof(wildcard_val), BPF_ANY);
				domains_array = NULL;
			}
		}

		cJSON *item;
		cJSON_ArrayForEach(item, domains_array)
		{
			const char *domain = cJSON_GetStringValue(item);
			if (!domain)
				continue;

			printf("[Debug]   Found domain: '%s'\n", domain);

			struct hostent *h = gethostbyname(domain);
			if (!h) {
				fprintf(stderr,
					"[Debug]   Warning: Could not resolve domain '%s'\n",
					domain);
				continue;
			}

			printf("[Debug]   -> Resolving... ");
			for (int j = 0; h->h_addr_list[j]; j++) {
				struct in_addr *addr = (struct in_addr *)h->h_addr_list[j];
				__u32 ip_h = ntohl(addr->s_addr); // Host byte order

				printf("%s ", inet_ntoa(*addr));

				// Add to allowed_ips map
				err = bpf_map__update_elem(skel->maps.allowed_ips, &ip_h,
							   sizeof(ip_h), &ip_h, sizeof(ip_h),
							   BPF_ANY);
				if (err) {
					fprintf(stderr,
						"\n[Debug]   -> ERROR adding IP to map: %s\n",
						strerror(errno));
				} else {
					printf("(Added) ");
				}
			}
			printf("\n");
		}
	} else {
		// FIX: Updated error message for clarity
		printf("[Loader] 'network_policies.allowed_domains' key not found or not an array.\n");
	}

	// --- 2. Populate Filesystem Policy (FS-001) ---
	printf("[Loader] Loading Filesystem Policies (FS-001)...\n");

	// FIX: Get the "filesystem_policies" object first
	cJSON *fs_policies = cJSON_GetObjectItem(root, "filesystem_policies");
	cJSON *write_dirs_array = NULL;
	if (cJSON_IsObject(fs_policies)) {
		// FIX: Get the array from that object
		write_dirs_array = cJSON_GetObjectItem(fs_policies, "allowed_write_dirs");
	}

	if (cJSON_IsArray(write_dirs_array)) {

		int array_size = cJSON_GetArraySize(write_dirs_array);

		if (array_size == 1) {
			cJSON *first = cJSON_GetArrayItem(write_dirs_array, 0);
			const char *write_dir = cJSON_GetStringValue(first);
			if (write_dir && strcmp(write_dir, "*") == 0) {
				printf("[Loader] FIlesystem wildcard detected\n");
				__u32 dir_key = TOGGLE_KEY_FS;
				__u32 wildcard_val = 1; // Value doesn't matter, just presence
				bpf_map__update_elem(skel->maps.policy_toggle_map, &dir_key, 
									sizeof(dir_key), &wildcard_val, sizeof(wildcard_val), BPF_ANY);
				write_dirs_array = NULL;
			}
		}

		cJSON *item;
		cJSON_ArrayForEach(item, write_dirs_array)
		{
			const char *path_str = cJSON_GetStringValue(item);
			if (!path_str)
				continue;

			printf("[Debug]   Found write dir: '%s'\n", path_str);

			// This struct MUST match the kernel definition
			struct {
				__u32 prefixlen;
				char path[MAX_PATH_LEN];
			} lpm_key;

			__builtin_memset(&lpm_key, 0, sizeof(lpm_key));
			// lpm_key.prefixlen = strlen(path_str);
			lpm_key.prefixlen = strlen(path_str) * 8;
			strncpy(lpm_key.path, path_str, MAX_PATH_LEN - 1);

			__u32 value = 1;

			printf("[Debug]   -> LPM key prefixlen: %u, path: %s\n", lpm_key.prefixlen,
			       lpm_key.path);

			// Add to allowed_write_paths map
			err = bpf_map__update_elem(skel->maps.allowed_write_paths, &lpm_key,
						   sizeof(lpm_key), &value, sizeof(value), BPF_ANY);
			if (err) {
				fprintf(stderr, "[Debug]   -> ERROR adding path to map: %s\n",
					strerror(errno));
			} else {
				printf("[Debug]   -> Successfully added path to map.\n");
			}
		}
	} else {
		// FIX: Updated error message for clarity
		printf("[Loader] 'filesystem_policies.allowed_write_dirs' key not found or not an array.\n");
	}

	// --- 3. Populate Security Policy (SEC-001) ---
	printf("[Loader] Loading Security Policies (SEC-001)...\n");

	// FIX: Get the "security_policies" object first
	cJSON *sec_policies = cJSON_GetObjectItem(root, "security_policies");
	cJSON *blocked_env_array = NULL;
	if (cJSON_IsObject(sec_policies)) {
		// FIX: Get the array from that object
		blocked_env_array = cJSON_GetObjectItem(sec_policies, "blocked_environment");
	}

	if (cJSON_IsArray(blocked_env_array)) {

		int array_size = cJSON_GetArraySize(blocked_env_array);

		if (array_size == 1) {
			cJSON *first = cJSON_GetArrayItem(blocked_env_array, 0);
			const char *env_var = cJSON_GetStringValue(first);
			if (env_var && strcmp(env_var, "*") == 0) {
				printf("[Loader] Environment wildcard detected\n");
				__u32 env_key = TOGGLE_KEY_ENV;
				__u32 wildcard_val = 1; // Value doesn't matter, just presence
				bpf_map__update_elem(skel->maps.policy_toggle_map, &env_key, 
									sizeof(env_key), &wildcard_val, sizeof(wildcard_val), BPF_ANY);
				blocked_env_array = NULL;
			}
		}

		cJSON *item;
		cJSON_ArrayForEach(item, blocked_env_array)
		{
			const char *key_str = cJSON_GetStringValue(item);
			if (!key_str)
				continue;

			printf("[Debug]   Found blocked env key: '%s'\n", key_str);

			char env_key[MAX_FORBIDDEN_LEN] = {};
			strncpy(env_key, key_str, MAX_FORBIDDEN_LEN - 1);
			__u32 value = 1;

			printf("[Debug]   -> Map key: '%s'\n", env_key);

			// Add to blocked_env_keys map
			err = bpf_map__update_elem(skel->maps.blocked_env_keys, &env_key,
						   sizeof(env_key), &value, sizeof(value), BPF_ANY);
			if (err) {
				fprintf(stderr, "[Debug]   -> ERROR adding env key to map: %s\n",
					strerror(errno));
			} else {
				printf("[Debug]   -> Successfully added env key to map.\n");
			}
		}
	} else {
		// FIX: Updated error message for clarity
		printf("[Loader] 'security_policies.blocked_environment' key not found or not an array.\n");
	}

	printf("[Loader] Policy loading complete.\n");
	cJSON_Delete(root);
	free(buffer);
	return 0;
}

int main(int argc, char **argv)
{
	struct handler_bpf *skel;
	struct ring_buffer *rb = NULL;
	int err;
    int inotify_fd;
	
	if (argc < 2)
	{
		fprintf(stderr, "Usage: %s <policy_json_file>\n",
			argv[0]);
			fprintf(stderr, "Example: %s policy.json \n", argv[0]);
			return 1;
	}
		
	const char *policy_path = argv[1];

	libbpf_set_print(libbpf_print_fn);

	skel = handler_bpf__open();
	if (!skel) {
		fprintf(stderr, "Failed to open BPF skeleton\n");
		return 1;
	}

	err = handler_bpf__load(skel);
	if (err) {
		fprintf(stderr, "Failed to load BPF skeleton: %d\n", err);
		goto cleanup;
	}

	// --- Populate eBPF Maps ---
	// err = populate_whitelist_map(skel);
	err = load_policy_from_json(skel, policy_path);
	if (err)
		goto cleanup;

	// --- Attach LSM modules ---
	err = handler_bpf__attach(skel);
	if (err) {
		fprintf(stderr, "Failed to attach BPF skeleton: %d\n", err);
		goto cleanup;
	}

	// --- Set up Ring Buffer ---
	/*
	 * FIX: Use bpf_map__fd() (with two underscores) to get the
	 * file descriptor for the ring buffer.
	 */
	rb = ring_buffer__new(bpf_map__fd(skel->maps.rb), handle_event, NULL, NULL);
	if (!rb) {
		err = -1;
		fprintf(stderr, "Failed to create ring buffer\n");
		goto cleanup;
	}

	printf("===========Ctrl+C to exit===========\n");

	// Handle Ctrl-C
    signal(SIGINT, sig_handler);
    signal(SIGTERM, sig_handler);


	// --- Set up inotify File Watcher ---
    inotify_fd = inotify_init1(IN_NONBLOCK);
    if (inotify_fd < 0) {
        perror("[Daemon] Failed to init inotify");
        goto cleanup;
    }

    // Watch for file modification or a close-after-write
    int wd = inotify_add_watch(inotify_fd, policy_path, IN_MODIFY | IN_CLOSE_WRITE);
    if (wd < 0) {
        fprintf(stderr, "[Daemon] Failed to add inotify watch on %s: %s\n", policy_path, strerror(errno));
        goto cleanup;
    }

    printf("[Daemon] Sandbox is active. Watching for policy violations and file changes...\n");
    printf("[Daemon] Press Ctrl+C to stop.\n");

	struct pollfd poller[1];
    poller[0].fd = inotify_fd;
    poller[0].events = POLLIN;


	while (!exiting) {
		// Poll with a timeout
		err = ring_buffer__poll(rb, 100 /* ms */);
		if (err == -EINTR) {
			err = 0;
			break;
		}
		if (err < 0) {
			printf("Error polling ring buffer: %d\n", err);
			break;
		}

		err = poll(poller, 1, 100);
		// Check for inotify events (Policy Hot-Reload)
        if (poller[0].revents & POLLIN) {
            fprintf(stderr, "\n[Daemon] Policy file '%s' changed. Reloading policies...\n", policy_path);
            
            // Reload the maps from the JSON file
            load_policy_from_json(skel, policy_path);

            // Drain the inotify fd to reset the event
            char notify_buf[4096];
            while (read(inotify_fd, notify_buf, sizeof(notify_buf)) > 0);
        }
	}

cleanup:
	if (inotify_fd >= 0) {
		inotify_rm_watch(inotify_fd, wd);
		close(inotify_fd);
	}
	ring_buffer__free(rb);
	handler_bpf__destroy(skel);
	return -err;
}
